// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADVGm9ykq7Wt9ElNcbxBQaRbppg9GIq18',
    appId: '1:429237501245:web:fc8f1113572340a4935954',
    messagingSenderId: '429237501245',
    projectId: 'confapp-3a6fd',
    authDomain: 'confapp-3a6fd.firebaseapp.com',
    storageBucket: 'confapp-3a6fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPJIh7NiM5t3bYAgZSwUhwLmEADeZwN30',
    appId: '1:429237501245:android:7b9b3065427497ea935954',
    messagingSenderId: '429237501245',
    projectId: 'confapp-3a6fd',
    storageBucket: 'confapp-3a6fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNlIJ_p2ihwGLQbLpi3ruAAbBNe6H2co',
    appId: '1:429237501245:ios:6000ab45cf9be1cb935954',
    messagingSenderId: '429237501245',
    projectId: 'confapp-3a6fd',
    storageBucket: 'confapp-3a6fd.firebasestorage.app',
    iosBundleId: 'com.example.confFutureTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpNlIJ_p2ihwGLQbLpi3ruAAbBNe6H2co',
    appId: '1:429237501245:ios:6000ab45cf9be1cb935954',
    messagingSenderId: '429237501245',
    projectId: 'confapp-3a6fd',
    storageBucket: 'confapp-3a6fd.firebasestorage.app',
    iosBundleId: 'com.example.confFutureTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADVGm9ykq7Wt9ElNcbxBQaRbppg9GIq18',
    appId: '1:429237501245:web:612de0df8a5a92d3935954',
    messagingSenderId: '429237501245',
    projectId: 'confapp-3a6fd',
    authDomain: 'confapp-3a6fd.firebaseapp.com',
    storageBucket: 'confapp-3a6fd.firebasestorage.app',
  );

}